# frozen_string_literal: true

source "https://rubygems.org"

git_source(:github) { |repo_name| "https://github.com/#{repo_name}" }

gem "require_all", "~> 3.0"


gem "colorize", "~> 0.8.1"

gem "pry", "~> 0.14.1"
